cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/', include('coupon.urls')),
    path('order/', include('order.urls')),
    path('', include('shop.urls')),
]

coupon/urls.py
from django.urls import path
from .views import add_coupon

app_name = 'coupon'

urlpatterns = [
    path('add/', add_coupon, name='add')
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(),name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(),name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(),name='order_validation'),
    path('complete/', order_complete,name='order_complete'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from .views import *

app_name = "shop"

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<slug:category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>', product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class AddProductForm(forms.Form):
    # quantity : 제품의 수량
    quantity = forms.IntegerField()
    
    # is_update : 상세 페이지에서 추가할 때와 장바구니에서 수량을 바꿀 때 동작하는 방식을 달리하기 위한 변수
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .forms import AddProductForm
from .cart import Cart
from coupon.forms import AddCouponForm


@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    # 제품의 정보는 상세 페이지 혹은 장바구니 페이지로부터 전달되며
    # AddProductForm을 통해 만들어진 데이터 입니다.
    form = AddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        # 제품 정보를 전달 받으면 카트 객체에 제품 객체를 추가합니다.
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    # 카트에서 제품을 삭제합니다.
    cart.remove(product)
    return redirect('cart:detail')


def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm() # 장바구니 페이지에 쿠폰 폼을 출력합니다.

    for product in cart:
        # 제품 수량 수정을 위해서 제품마다 폼을 하나씩 추가해 줍니다.
        # 수량은 수정하는 대로 반영해야 하기 때문에 is_update 값을 True로 설정했습니다.
        product['quantity_form'] = AddProductForm(initial={'quantity':product['quantity'], 'is_update':True})

    return render(request, 'cart/detail.html', {'cart':cart, 'add_coupon':add_coupon})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Shopping cart
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Remove</th>
                <th scope="col">Unit price</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <th scope="row">
                    <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}" class="img-thumbnail">
                    </a>
                </th>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url "cart:product_add" product.id %}" method="post">
                        {{ item.quantity_form.quantity }}
                        {{ item.quantity_form.is_update }}
                        <input type="submit" class="btn btn-primary" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td><a href="{% url "cart:product_remove" product.id %}">Remove</a></td>
                <td class="num">${{ item.price }}</td>
                <td class="num">${{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}

        {% comment %}         
        쿠폰이 있을 경우만 할인에 관한 정보를 출력합니다.
        {% endcomment %}
        {% if cart.coupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td >${{ cart.get_product_total }}</td>
            </tr>
            <tr>
                    <td>"{{ cart.coupon.code }}" coupon (${{ cart.coupon.amount }})</td>
                <td colspan="4"></td>
                <td >- ${{ cart.get_discount_total|floatformat:"2" }}</td>
            </tr>
        {% endif %}
        
        {% comment %}         
        총 합계 금액을 출력하는 부분의 메서드는 get_total_price를 사용합니다.
        {% endcomment %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price|floatformat:"2" }}</td>
        </tr>
        </tbody>
    </table>

    {% comment %}     
    쿠폰 코드를 입력하는 폼을 출력합니다.
    {% endcomment %}
    <p>
        Add Coupon:
    </p>
    <form action='{% url "coupon:add" %}' method="post">
        {{ add_coupon }}
        <input type="submit" value="Add">
        {% csrf_token %}
    </form> 
     


    <p class="text-right">
        <a href='{% url "shop:product_all" %}' class="btn btn-secondary">Continue shopping</a>
        <a href='{% url "orders:order_create" %}' class="btn btn-primary">Checkout</a>
    </p>
{% endblock %}